### PR TITLE
BSM tests

### PR DESCRIPTION
**Pull request by alecloudenback**
Why is the test not passing?

### CODE REVIEW

**Comment by kasperrisager** [comment]
The build is complaining about `LogNormal` not existing. Is it just a namespace issue?

**Comment by alecloudenback** [comment]
> The build is complaining about `LogNormal` not existing. Is it just a namespace issue?

I fixed the PR to capture the tests I was doing locally and added some comments on what I was trying to test

**Comment by kasperrisager** [comment]
> I fixed the PR to capture the tests I was doing locally and added some comments on what I was trying to test

I can't seem to see that in this pr. Am I looking in the right place?

**Comment by alecloudenback** [comment]
> I can't seem to see that in this pr. Am I looking in the right place?

My bad, forgot to push the commit.

**Comment by kasperrisager** [comment]
The p value of the test is 5e-128, so something is way off. I think it's the mean of the lognormal that needs to have `m.q` subtracted. Also, I don't remember the formula precisely, but sigma^2 are almost always divided by 2 when seen in the wild 🙂. 

Also, the expected distribution is only lognormal in the limit of infinitely small timesteps, so with 60 timesteps, 10,000 replications might be enough to reveal that the distribution is a product of 60 normal distributions.

**Pull request merged**
